title: "Mukesh Rai"
description: "I would like to answer the scientific questions in the atmospheric science field using observation data, modeling, and satellite product."
site_title: 'Mukesh Rai &#187;&#187; &#174;mukeshraee2&#169;22'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: mukeshraeee
blog_url: http://mukeshraee.blogspot.com/
email: mukeshraeee@gmail.com
keybase_username: mukeshraeee
twitter_username: mukeshraee
instagram_username: mukesh_raee
linkedin_username: mukesh-rai-5b5b3b85

#reddit_username: abhn

# absolute or relative
profile_picture: assets/images/M.jpg

# Google Analytics ID
google_analytics: 
