title: Mr. Mukesh Rai
description: "Atmospheric modeler, travel nerd, phototgraphy enthusiastic, fond of indie trand song"
site_title: '@mukeshrai - Mukesh Rai'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: mukeshraeee
blog_url: http://mukeshraee.blogspot.com/
email: mukeshraeee@gmail.com
keybase_username: mukeshraeee
twitter_username: mukeshraee
#reddit_username: abhn

# absolute or relative
profile_picture: assets/images/M.jpg

# Google Analytics ID
google_analytics: 
