title: "Mukesh Rai"
description: "Mukesh holds masters in Environmental science and glaciology. He is doing PhD in University of Chinese Academy of Science [atmospheric modeling]. His interest align with modeling work, satellite data, and reanalys product. He has been working in aerosol transport mechanism, radiative-climate, and aerosol-pbl feeback. He is kind of outdoor guy who loves to travel, take phototgraph, fond of indie trad song, and amateur ukulele player."
site_title: 'Mukesh Rai &#187;&#187; &#174;mukeshraee2&#169;22'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: mukeshraeee
blog_url: http://mukeshraee.blogspot.com/
email: mukeshraeee@gmail.com
keybase_username: mukeshraeee
twitter_username: mukeshraee
instagram_username: mukesh_raee
linkedin_username: mukesh-rai-5b5b3b85

#reddit_username: abhn

# absolute or relative
profile_picture: assets/images/M.jpg

# Google Analytics ID
google_analytics: 
