title: "Mukesh Rai"
description: "Atmospheric modeler, travel nerd, phototgraphy enthusiastic "
site_title: '@mukeshrai - Mukesh Rai'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: mukeshraeee
blog_url: https://www.nagekar.com
email: mukeshraeee@gmail.com
keybase_username: mukeshraeee
twitter_username: mukeshraee
#reddit_username: abhn

# absolute or relative
profile_picture: assets/images/M.jpg

# Google Analytics ID
google_analytics: 
